export const ROUTES = {
  login: 'Login',
  verifyPhone: 'VerifyPhone',
  viewProduct: 'ViewProduct',
  cart:'Cart',
  verifyOtp: 'VerifyOtp',
  resetPassword: 'ResetPassword',
  register: 'Register',
  home: 'Home',
  products: 'Products',
  invest: 'Invest',
  profile: 'Profile',
  settings: 'Settings',
  profileSettings: 'Profile Settings',
  password: 'Change Password',
  nominee: 'Nominee Details',
  bank: 'Bank Settings',
  wallet: 'Wallet',
  help: 'Help',
  about: 'About',
  share: 'Share',
  terms: 'Terms',
  privacy: 'Privacy',
  order:'My Order',
  orderDetails:'Order Details',
  feedback:'Feedback'

};
